[package]
name = "rayon-adaptive"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@imag.fr>"]

[dev-dependencies]
criterion="*"

[features]
# enable this to log using rayon_logs
logs = ["rayon_logs"]

[dependencies]
rayon_logs={version="*", optional=true}
rayon="*"
itertools="*"
rand="*"

[[bench]]
name = "merge_sort"
harness = false

[[bench]]
name = "prefix"
harness = false
