[package]
name = "rayon-adaptive"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@imag.fr>"]

[dev-dependencies]
criterion="*"

[dependencies]
rayon_logs={path="../rayon-logs"}
rayon="*"
itertools="*"
rand="*"

[[bench]]
name = "merge_sort"
harness = false

